################### HTTP Configuration   ##########################
server:
  web:
    port: 443
    sslEnable: true
    sslKeyType: pfx
    sslKeyStore: /opt/wechat/thekeystore
    sslPassword: changeit
spring:
  profiles:
    active: [wechat,atomSrv,database,wechat-app]

################### Vert.x Configuration ##########################
vertx:
  worker:
    pool:
      size: 4
  workerVerticle:
    instances: 2
  clusterMode: hazelcast1
  scanPath: pers.welisdoon.webserver
  dns:
    enable: false
    ip: 134.192.232.18,134.192.232.17
    maxQueries: 10
