################### HTTP Configuration   ##########################
server:
  port: 8088
  https-enable: false
spring:
  profiles:
    active: [wechat,atomSrv]

################### Vert.x Configuration ##########################
vertx:
  worker:
    pool:
      size: 4
  workerVerticle:
    instances: 2
  clusterMode: hazelcast
  scanPath: pers.welisdoon.webserver
  dns:
    enable: true
    ip: 134.192.232.18,134.192.232.17
    maxQueries: 10
