################### HTTP Configuration   ##########################

spring:
  profiles:
    active: [atomSrv,database,wechat-app,order-flow]
  main:
    web-application-type: none
################### Vert.x Configuration ##########################

vertx:
  webs:
    main:
      port: 443
      sslEnable: true
      sslKeyType: pfx
      sslKeyStore: /opt/wechat/thekeystore
      sslPassword: e75M8y7K
      sslKeyPath:
  worker:
    pool:
      size: 4
  workerVerticle:
    instances: 2
  clusterMode: hazelcast1
  dns:
    enable: false
    ip: 134.192.232.18,134.192.232.17
    maxQueries: 10
  scheduler: true


#logging:
#  level:
#    root: "trace"
#    appdao: "trace"
#  group:
#    appdao: ",org.springframework.jdbc,org.mybatis"