################### HTTP Configuration   ##########################
server:
  web:
    port: 443
    sslEnable: true
    sslKeyType: pfx
    sslKeyStore: /opt/wechat/thekeystore
    sslPassword: e75M8y7K
    sslKeyPath:
    staticPath: /opt/wechat/tempPic
spring:
  profiles:
    active: [atomSrv,database,wechat-app]
  main:
    web-application-type: none
################### Vert.x Configuration ##########################

vertx:
  worker:
    pool:
      size: 4
  workerVerticle:
    instances: 2
  clusterMode: hazelcast1
  dns:
    enable: false
    ip: 134.192.232.18,134.192.232.17
    maxQueries: 10


#logging:
#  level:
#    root: "trace"
#    appdao: "trace"
#  group:
#    appdao: ",org.springframework.jdbc,org.mybatis"