wechat-app:
  appID: wx366b88b818ee0b33
  appsecret: db69bf9effa3fbb0b53483565a7e1baa
  token: 9dvL9Kze96Oc76XhMUeI03LTZ29
  key: AC32OLzYAjjkPqzxilsPiMPbqYCHESnOuPzyYpjFyVw
  afterUpdateTokenTime: 6000
  orderCycleTime: 0
  mchId: xxxx
  mchKey: xxx
  appName: 爱车智联AUTOCAR
  address: https://www.welisdoon.xyz
  path:
    pay: /wxAppPay
    app: /wxApp
    push: /push
  urls:
    getAccessToken: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=${wechat-app.appID}&secret=${wechat-app.appsecret}
    code2Session: https://api.weixin.qq.com/sns/jscode2session?appid=${wechat-app.appID}&secret=${wechat-app.appsecret}&grant_type=authorization_code&js_code=
    unifiedorder: https://api.mch.weixin.qq.com/pay/unifiedorder
temp:
  filePath: /opt/wechat/tempPic