wechat:
  appID:
  appsecret:
  token:
  key:
  afterUpdateTokenTime: 6000
  urls:
    base: https://api.weixin.qq.com
    sendToUser: /cgi-bin/message/custom/send?access_token=${wechat.token}
    getToken: /cgi-bin/token
    getIPs: /cgi-bin/getcallbackip?access_token=${wechat.token}
  schedul:
    power: on
    delay: 300000
