wechat:
  appID: wx675824e3f240da6d
  appsecret: b2f4490e7f14bf60edc3bbe854ce70c1
  token: 9dvL9Kze96Oc76XhMUeI03LTZ29
  key: AC32OLzYAjjkPqzxilsPiMPbqYCHESnOuPzyYpjFyVw
  afterUpdateTokenTime: 6000
  urls:
    getAccessToken: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=${wechat-app.appID}&secret=${wechat-app.appsecret}
    code2Session: https://api.weixin.qq.com/sns/jscode2session?appid=${wechat-app.appID}&secret=${wechat-app.appsecret}&grant_type=authorization_code&js_code=
    unifiedorder: https://api.mch.weixin.qq.com/pay/unifiedorder
    subscribeSend: https://api.weixin.qq.com/cgi-bin/message/subscribe/send?access_token=
  schedul:
    power: on
    delay: 300000
